Fixes #34630 - Errata Filters Date do not show "Start Date" & "End Date"
Katello/katello pull request #10024
Opened 2022-03-16 20:06 UTC by Andrewgdewar

#### What are the changes introduced in this pull request?

- Updated invalid date error text
- Made the placeholder text dynamic to act as label.

#### What are the testing steps for this pull request?

- Create both types of errata filters
- Enter an invalid date, view copy.
- onFocus the placeholder text should convert to the expected date format
- onBlur the placeholder should return to its label (start or end date) if input left blank

2022-03-17 15:50 UTC, jeremylenz commented
![date_filled-out](https://user-images.githubusercontent.com/22042343/158839204-5ae82ab1-5ef8-432b-bcb1-1103dcee167e.png)

After the dates are entered, it's no longer apparent what the fields are for. This means one cannot "confirm the current user inputs" as mentioned in the original bug.

2022-03-18 12:48 UTC, MariSvirik commented
@Andrewgdewar @jeremylenz 
What about this :

<img width="951" alt="Screenshot 2022-03-18 at 13 38 13" src="https://user-images.githubusercontent.com/51960547/159004588-7e588237-6e38-4733-b1d5-43f5dceca61b.png">

<img width="932" alt="Screenshot 2022-03-18 at 13 41 32" src="https://user-images.githubusercontent.com/51960547/159005576-074ee0fb-15a9-43b8-8614-9afcad518a1f.png">


• Add "to" between the fields
• Add "from" to the dropdown to display Issued from/Updated from ( it's always going to be range in this page) OR instead add "From" before the start date picker.
• Let's use from/to in a chip as well: "Updated from MM/DD/YYYY to MM/DD/YYYY"

Helper text if entering invalid format: "Enter a valid format: MM/DD/YYYY" 
Fix sentence case for Start date/End date

2022-03-18 13:39 UTC, jeremylenz commented
> What about this

It both allows us to benefit from the work @Andrewgdewar has already put in here, and improves on the design to address the original concern. I think this will be a great solution! :+1:

2022-03-18 15:13 UTC, Andrewgdewar commented
> @Andrewgdewar @jeremylenz What about this :
> 
> <img alt="Screenshot 2022-03-18 at 13 38 13" width="951" src="https://user-images.githubusercontent.com/51960547/159004588-7e588237-6e38-4733-b1d5-43f5dceca61b.png">
> 
> <img alt="Screenshot 2022-03-18 at 13 41 32" width="932" src="https://user-images.githubusercontent.com/51960547/159005576-074ee0fb-15a9-43b8-8614-9afcad518a1f.png">
> 
> • Add "to" between the fields • Add "from" to the dropdown to display Issued from/Updated from ( it's always going to be range in this page) OR instead add "From" before the start date picker. • Let's use from/to in a chip as well: "Updated from MM/DD/YYYY to MM/DD/YYYY"
> 
> Helper text if entering invalid format: "Enter a valid format: MM/DD/YYYY" Fix sentence case for Start date/End date

Sounds good, with the exception that one does not enter a format, they enter text. A format is MM/DD/YYYY.  Alternative copy @jeremylenz?

2022-03-18 15:19 UTC, jeremylenz commented
> Sounds good, with the exception of the helper text change: one does not enter a format, they enter text. A format is MM/DD/YYYY

How about `Enter a date in the format MM/DD/YYYY` ?

2022-03-18 15:21 UTC, jeremylenz commented
> How about `Enter a date in the format MM/DD/YYYY` ?

Not to complicate things, but what if the user's locale is set to one that uses a different date format? Will this date picker always use the same format? Will it use the local format and this label will be inaccurate?

2022-03-18 15:26 UTC, Andrewgdewar commented
\

> > How about `Enter a date in the format MM/DD/YYYY` ?
> 
> Not to complicate things, but what if the user's locale is set to one that uses a different date format? Will this date picker always use the same format? Will it use the local format and this label will be inaccurate?

Currently all of the pickers in the app MM/DD/YYYY (Without translation)

2022-03-18 15:27 UTC, jeremylenz commented
> Currently all of the pickers in the app MM/DD/YYYY (Without translation)

too bad! I suppose that's not in scope here though, so I won't block this on it.

2022-03-18 16:24 UTC, MariSvirik commented
> > How about `Enter a date in the format MM/DD/YYYY` ?
> 
> Not to complicate things, but what if the user's locale is set to one that uses a different date format? Will this date picker always use the same format? Will it use the local format and this label will be inaccurate?

I thought it would change automatically based on the user preferences. My bad. In any case, the accepted/valid format inside the date picker and the suggested correct format displayed in the helper text should be the same. Consistency FTW!

The point of the helper text was to give users precise information about what went wrong and how to fix it.
This is the copy from the [PF4 guidelines](https://www.patternfly.org/v4/components/date-picker/design-guidelines) - "Enter a valid date: MM/DD/YYYY" But I'm fine with @jeremylenz's suggestion.

2022-03-18 17:54 UTC, Andrewgdewar commented
<img width="894" alt="Screen Shot 2022-03-18 at 11 53 51 AM" src="https://user-images.githubusercontent.com/38083295/159057255-087c39d0-6b8d-4bbb-a736-b5deb86a2b37.png">
<img width="836" alt="Screen Shot 2022-03-18 at 11 26 05 AM" src="https://user-images.githubusercontent.com/38083295/159057281-133b0730-707f-4bdb-81b3-8417f5d5dbc0.png">
<img width="901" alt="Screen Shot 2022-03-18 at 11 52 11 AM" src="https://user-images.githubusercontent.com/38083295/159057300-c4c15e08-804c-4453-b374-dc225b4f2fc0.png">

2022-03-18 18:12 UTC, jeremylenz requested changes

2022-03-18 18:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Filters/CVErrataDateFilterContent.js
> +                    placeholder={startEntry ? 'MM/DD/YYYY' : __('Start Date')}
```suggestion
                    placeholder={startEntry ? 'MM/DD/YYYY' : __('Start date')}
```

2022-03-18 18:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Filters/CVErrataDateFilterContent.js
> +                    placeholder={endEntry ? 'MM/DD/YYYY' : __('End Date')}
```suggestion
                    placeholder={endEntry ? 'MM/DD/YYYY' : __('End date')}
```

2022-03-18 18:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Filters/CVErrataDateFilterContent.js
> +  const invalidDateFormat = __('Enter a valid date: MM/DD/YYYY');
:+1: :+1:

2022-03-18 18:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Filters/CVErrataIDFilterContent.js
> +                        placeholder={startEntry ? 'MM/DD/YYYY' : __('Start Date')}
```suggestion
                        placeholder={startEntry ? 'MM/DD/YYYY' : __('Start date')}
```

2022-03-18 18:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Filters/CVErrataIDFilterContent.js
> +                        placeholder={endEntry ? 'MM/DD/YYYY' : __('End Date')}
```suggestion
                        placeholder={endEntry ? 'MM/DD/YYYY' : __('End date')}
```

2022-03-21 14:03 UTC, jeremylenz approved these changes
Changes look good, thanks @Andrewgdewar !

ACK :+1:

2022-03-21 14:58 UTC, Andrewgdewar commented
> 
@jeremylenz 
Thank you good sir!

2022-03-21 15:47 UTC, merged