Fixes #35012 - add call-to-action empty states
Katello/katello pull request #10144
Opened 2022-06-02 20:07 UTC by tazhibaevaaliya

#### What are the changes introduced in this pull request?
Added call-to-actions for empty state on Host collections (under Host Overview Tab), Module Streams (under Content Tab), Repository sets, and Host content view selection (under Host Overview Tab -> Content View Details) pages/tabs

#### Considerations taken when implementing this change?
I believe that adding call-to-actions will increase user experience whenever they are no existing/available items/products/repos to show

#### What are the testing steps for this pull request?
For all the corresponding tabs:
1. Navigate to the corresponding tab/page 
2. Assuming that you do not have available/existing items to show, you should see action button(s) (the number of action buttons depends on different number of the ways you can create a specific item/product/repo), which should direct you to the creation page
3. Try adding some items and searching for non-existing item. You should see a message indicating that such item does not exist without call-to-action button(s) 

Note: there is a separate card created for the last action item (empty search)

2022-06-02 20:12 UTC, jeremylenz commented
[test katello]

2022-06-07 18:53 UTC, jeremylenz requested changes
Thanks @tazhibaevaaliya!

I'll let @lfu do the testing etc. but wanted to leave some code comments below.

Also, seems like the React tests will need some work!

2022-06-07 18:53 UTC, jeremylenz commented on webpack/components/Table/EmptyStateMessage.js
> +  ({ secondaryActionLink } = extraTableProps);
We never got around to going over this, but here's the simpler way to write it:

```js
const { primaryActionTitle, showPrimaryAction, showSecondaryAction,
secondaryActionTitle, primaryActionLink, secondaryActionLink } = extraTableProps;
```

see the "Basic assignment" section here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment#object_destructuring

2022-06-07 18:53 UTC, jeremylenz commented on webpack/components/Table/EmptyStateMessage.js
> +/* eslint-disable prefer-const */
See the previous comment for a way to write this where you won't have to disable this rule. :)

2022-06-07 18:53 UTC, jeremylenz commented on webpack/components/Table/MainTable.js
> +  const emptyStateProps = { ...extraTableProps };
Why make a copy of `extraTableProps`?

2022-06-07 18:53 UTC, jeremylenz commented on webpack/components/Table/TableWrapper.js
> +        // {...emptyStateProps}
leftover?

2022-06-07 18:53 UTC, jeremylenz commented on webpack/components/extensions/HostDetails/Tabs/RepositorySetsTab/RepositorySetsTab.js
> +  const primaryActionTitle = __('Enable Red Hat Repositories');
```suggestion
  const primaryActionTitle = __('Enable Red Hat repositories');
```

2022-06-07 19:43 UTC, lfu commented on webpack/components/Table/MainTable.js
> +        {...emptyStateProps}
Could we remove the above line where `emptyStateProps` is set and call here directly `{...extraTableProps}` ?

2022-06-07 19:44 UTC, lfu commented on webpack/components/Table/TableWrapper.js
> +        // {...emptyStateProps}
Are these all commented out? Do we need to keep them here?

2022-06-07 19:51 UTC, lfu commented
Seems duplicated @jeremylenz's comments :)

Tests looked well for RHEL hosts. 

But Debian hosts would get the same page for `Repository sets` and `Module streams` which seem not appropriate. Any thought? @jeremylenz

2022-06-07 20:05 UTC, jeremylenz commented
> But Debian hosts would get the same page for Repository sets and Module streams which seem not appropriate. Any thought?

Hmm..  We could maybe check if the deb content type is enabled and not show the RH Repos link if so? @ianballou would that even work?  I would consider it extra credit either way.

2022-06-07 20:17 UTC, tazhibaevaaliya commented
@jeremylenz @lfu What is the best way to incorporate your comments? Should I manually add and make another commit or there is an easier way?

2022-06-07 20:29 UTC, jeremylenz commented
If you want to keep it squashed, you can make your changes and then
```
git add .
git commit --amend --no-edit
```
and force push.

If you want to add a commit instead, you can just add it and then do a regular push.  I'm fine with either one :+1:

2022-06-07 20:36 UTC, ianballou commented
> Hmm.. We could maybe check if the deb content type is enabled and not show the RH Repos link if so? @ianballou would that even work? I would consider it extra credit either way.

Debian is installed by default, so likely few upstream users would see this RH Repos link then.

Is there a fact or something that we could grab from the API to determine that the host is a RHEL one?

At least in Rails you can do `::Host.find(<id>).os` which returns a `Redhat` object for my RHEL 7 host. Not sure if we expose that in the API.

2022-06-07 20:42 UTC, jeremylenz commented
Looks like the host details provides `operatingsystem_name` property:

```
operatingsystem_id: 4
operatingsystem_name: "RedHat 8.5"
```

We could see if that string contains "RedHat". Kinda hacky, but would save us another API request. thoughts?

2022-06-07 20:45 UTC, ianballou commented
> We could see if that string contains "RedHat". Kinda hacky, but would save us another API request. thoughts?

Here's the old logic for determining if a host is a Debian one: https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host.factory.js#L30

2022-06-07 20:47 UTC, jeremylenz commented
Love it :laughing:

2022-06-07 20:48 UTC, tazhibaevaaliya commented
@ianballou @jeremylenz @lfu Will we need to create a separate card for this issue then?

2022-06-07 20:50 UTC, tazhibaevaaliya commented
Also, quick question, once I committed, should I rebase once more to pick up the latest commit in my emptySearch/35027-add-link-to-clear-search branch? @jeremylenz

2022-06-07 20:54 UTC, jeremylenz commented
> should I rebase once more to pick up the latest commit in my emptySearch/35027-add-link-to-clear-search branch?

It's up to you. You'll have to fix any conflicts either way -- you're just choosing to do it later, when this PR is merged, or now if you decide to rebase. :)

2022-06-07 20:56 UTC, tazhibaevaaliya commented
@jeremylenz Yay! I just rebassing :smile:

2022-06-08 13:35 UTC, lfu commented on webpack/components/Table/TableWrapper.js
> -
One way is to add the line back, then follow this [comment](https://github.com/Katello/katello/pull/10144#issuecomment-1149135241).

2022-06-08 18:18 UTC, lfu commented
APJ

2022-06-08 18:19 UTC, jeremylenz commented
[test katello]

2022-06-09 17:07 UTC, jeremylenz commented
[test katello]

2022-06-09 18:16 UTC, lfu approved these changes
LGTM 👍🏻

2022-06-09 18:24 UTC, jeremylenz approved these changes
Great work @tazhibaevaaliya!

ACK :+1:

2022-06-09 20:18 UTC, merged

2022-06-10 14:11 UTC, tazhibaevaaliya commented
@jeremylenz Thank you for all your help!