Fixes #35265 - When toggling SCA, change the owner and don't refresh manifest
Katello/katello pull request #10208
Opened 2022-07-22 20:34 UTC by lfu

#### What are the changes introduced in this pull request?
1. Don't refresh manifest when toggling SCA on the Organization edit page
2. To toggle SCA on an org, hit the /candlepin/owners endpoint and not the consumers/:uuid.

#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?
Verify simple content access toggling on organization works.

2022-07-25 16:49 UTC, jeremylenz requested changes
Thanks for the thorough testing 👍🏻 
This PR only changed the API endpoint for SCA enable/disable toggle action.
Just Edit an organization, toggle the SCA setting and verify the setting is set correctly.
You may got to Subscriptions page to check if SCA is enabled or not after editing organization.

2022-07-25 16:52 UTC, jeremylenz commented
ignore that review; I had the wrong branch checked out :yum: 

will test again after lunch

2022-07-25 20:14 UTC, jeremylenz reviewed
Thanks @lfu!

After testing again on the right branch:

:heavy_check_mark: Toggling SCA does not plan any upstream actions
:heavy_check_mark: Host `subscription-manager status` reports SCA on or off as expected

My thoughts:

1. The message about refreshing the manifest should be removed from the Organization Edit page
2. Now that `Actions::Katello::Organization::SimpleContentAccess::Enable` and `Actions::Katello::Organization::SimpleContentAccess::Disable` don't plan any sub-actions, should this action be taken out of Dynflow entirely?
3. When importing a new manifest, or refreshing a manifest, as a user I would expect to see the SCA status of the imported manifest reflect that of the subscription allocation on the Portal. However, after disabling SCA in Katello and refreshing, my manifest still showed disabled in Katello and enabled on the Portal.  Should the manifest import action be updated to sync the Katello owner with the imported SCA status? Or should we leave it entirely independent? Now that the consumer / manifest is no longer tied to SCA, I'm wondering what that toggle on the portal is even for...

2022-07-26 16:51 UTC, jeremylenz commented
> 1. The message about refreshing the manifest should be removed from the Organization Edit page

This is covered by https://github.com/Katello/katello/pull/10211

and we decided to keep the Dynflow action. So the only remaining comment is about the toasts.

2022-07-26 17:10 UTC, lfu commented
> 1. The message about refreshing the manifest should be removed from the Organization Edit page

This would be addressed by https://issues.redhat.com/browse/SAT-11846 which will modify Edit organization page.

> 2. Users should only receive a single toast notification after toggling SCA

There are lots of other attributes are picked up for update when only SCA checkbox is touched on Edit organization page. 
This concern should be addressed as well by https://issues.redhat.com/browse/SAT-11846 in my opinion.

> 3. Now that `Actions::Katello::Organization::SimpleContentAccess::Enable` and `Actions::Katello::Organization::SimpleContentAccess::Disable` don't plan any sub-actions and don't contact upstream Candlepin, should this action be taken out of Dynflow entirely?

As discussed in today's standup meeting, it will be kept in Dynflow as it is.

2022-07-26 17:22 UTC, jeremylenz commented
> There are lots of other attributes are picked up for update when only SCA checkbox is touched on Edit organization page.
This concern should be addressed as well by https://issues.redhat.com/browse/SAT-11846 in my opinion.

@chris1984 can you take care of removing the additional toast notification in your PR?

2022-07-26 17:28 UTC, chris1984 commented
> > There are lots of other attributes are picked up for update when only SCA checkbox is touched on Edit organization page.
> > This concern should be addressed as well by https://issues.redhat.com/browse/SAT-11846 in my opinion.
> 
> @chris1984 can you take care of removing the additional toast notification in your PR?

@jeremylenz yeah I can

2022-07-26 17:30 UTC, jeremylenz approved these changes
Thanks @lfu and @chris1984!

ACK :+1:

2022-07-26 18:13 UTC, merged