Fixes #35191 - Strip errata trailing whitespace before saving
Katello/katello pull request #10372
Opened 2022-12-01 20:16 UTC by wbclark

#### What are the changes introduced in this pull request?

Strip trailing whitespace from errata description, title, etc before saving, to avoid discrepancy between pulp record vs. katello record

#### Considerations taken when implementing this change?

I believe this still leaves an "extra" record in pulp when it already existed, but it will prevent existing errata in Katello from being wrongly determined as "new" since they will now have an exactly matching pulp record.

NOTE: Since https://github.com/Katello/katello/commit/e626c4ce9078ddfd36bfe3216a85bacc96427212 we should not send email notifications any longer when the repository_errata list is unchanged.

#### What are the testing steps for this pull request?

See https://projects.theforeman.org/issues/35191 but note that the _symptom_ described there should already be resolved by https://github.com/Katello/katello/commit/e626c4ce9078ddfd36bfe3216a85bacc96427212

2022-12-09 13:49 UTC, chris1984 commented
[test katello]

2022-12-13 21:56 UTC, jeremylenz commented
[test katello]

2022-12-15 20:57 UTC, chris1984 commented
[test katello]

2022-12-15 21:24 UTC, chris1984 requested changes
@wbclark Me and @jeremylenz kicked off the pipeline twice and the same 6 tests are failing. It looks like your changes have caused the test failure since on master these are passing.

2023-01-31 20:55 UTC, wbclark commented
@chris1984 @jeremylenz I'm pretty confident in the code change but I'm not sure why the tests are failing or if I've updated them correctly. Would one of you have some time to look into this with me?

2023-01-31 22:52 UTC, jeremylenz commented
[test katello]

2023-02-07 15:50 UTC, wbclark commented
```
Archive JUnit-formatted test results<1s

[2023-02-06T19:20:38.339Z] Recording test results

[2023-02-06T19:20:38.351Z] No test report files were found. Configuration error?

No test report files were found. Configuration error?
```

I believe this is unrelated to my change (and it was green before I pushed typo that should not have caused this)

2023-02-07 15:51 UTC, jeremylenz commented
[test katello]

2023-02-20 22:26 UTC, ianballou approved these changes

2023-02-20 22:29 UTC, chris1984 approved these changes
ACK, looks good

2023-02-20 22:29 UTC, merged