Fixes #35919 - Change content source UX improvements
Katello/katello pull request #10408
Opened 2023-01-11 09:43 UTC by stejskalleos

#### What are the changes introduced in this pull request?

- Added bread crumb navigation
- When no hosts are found, still show title & bread-crumb nav
- Form button changed to "Update"
- Notification changed to `info` with steps what to do next

![ccs](https://user-images.githubusercontent.com/59385976/211771837-e8c6aff5-6b89-402d-aa6f-3b1050d8ca06.png)

#### Considerations taken when implementing this change?
- https://projects.theforeman.org/issues/35919
- Discussion with UX team

#### What are the testing steps for this pull request?
- Go to hosts
- Select host with content source
- Select Change content source from actions
- Check the Form

2023-01-11 11:41 UTC, stejskalleos commented
Hi @jeremylenz, could you please do the review? It's another follow up UX PR to https://github.com/Katello/katello/pull/10297

2023-01-12 19:25 UTC, jeremylenz reviewed
thanks @stejskalleos!  Some comments below

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/components/ContentSourceTemplate.js
> +        <Alert variant="info" title="Hosts successfully updated" className="margin-top-20">
Title needs to be translated.

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/components/ContentSourceTemplate.js
> +        </Alert>
To ensure proper translation, please use `<FormattedMessage>` similar to https://github.com/Katello/katello/blob/47492881d123b13c2e7973c4e1db965971d45657/webpack/scenes/Subscriptions/SubscriptionsPage.js#L223-L235

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +              { caption: 'Change host content source' },
When changing content source for a single host, can that host be added to the breadcrumbs here?

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +  const noSearch = getHostIds(urlParams.host_id).length === 0 && urlParams.searchParam === '';
```suggestion
  const noHostSpecified = getHostIds(urlParams.host_id).length === 0 && urlParams.searchParam === '';
```

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +                title={__('No hosts with content source found!')}
```suggestion
                title={__('No hosts were specified')}
```

2023-01-12 19:25 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +              contentHosts={contentHosts}
When I change `host_id=` to a bogus ID, I get a `<ContentSourceForm>` but everything is disabled. That case should probably display the error alert instead.

2023-01-13 11:58 UTC, MariSvirik commented
@stejskalleos 
If you are using an alert within a form, you should use an inline alert - view in [PF4 guidelines here](https://www.patternfly.org/v4/components/alert/design-guidelines#using-bordered-inline-alerts).
What's more, after discussion with the content team we came up with this alert to make it super obvious that the source hasn't been changed yet. 

<img width="913" alt="Screenshot 2023-01-13 at 12 46 36" src="https://user-images.githubusercontent.com/51960547/212313850-9eba8d11-4c90-4f06-ac6d-ea2932466511.png">

Also, after the button "Update" is clicked and an alert appears, make the button disabled. Otherwise, the "Update" button is a visually primary action even though at this point we want the users to run REX and not repeatedly click on "Update".

There were also, suggestions about changing the button name to "Continue" or "Next" but I would dismiss these suggestions for now.

2023-01-16 09:42 UTC, stejskalleos commented
@MariSvirik @jeremylenz PR updated:

- Show alert when host_id is not existing
- Disable Update button after form is submitted
- Alert is `warning` instead of `info`, changed texts
- Bread crumb navigation goes to host or hosts
![ccs_monday](https://user-images.githubusercontent.com/59385976/212647038-494d7c88-e9c8-4392-a2eb-bc7510ed6a9e.png)

2023-01-16 14:49 UTC, jeremylenz requested changes
On the CV UI and host detail page, there's a nice banner that shows if no content views are available for the selected environment:

![image](https://user-images.githubusercontent.com/22042343/212705335-ee155f9c-9700-4b8d-9dbe-b2e1a52f6e9d.png)

---
Would be nice to add that banner here as well.

I would also eventually like to use the same interface overall here (see ChangeHostCVModal.js) but that's probably not in scope here, plus it'll be changing as the multi-CV work progresses.

Some more comments below

2023-01-16 14:49 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/components/ContentSourceTemplate.js
> +        <Alert variant="warning" title={__('Hosts configurations are not updated yet')} className="margin-top-20" isInline>
```suggestion
        <Alert variant="warning" title={__('Host configurations are not updated yet')} className="margin-top-20" isInline>
```

2023-01-16 14:49 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +  const breadcrumbItems = () => {
If it's a single host the breadcrumb should be

```
Hosts > hostname > Change host content source
```

with "Hosts" and "hostname" as links.
If it's multiple hosts the breadcrumb can remain

```
Hosts > Change host content source
```
with "Hosts" as the link.

@MariSvirik can check me, but I think this is how breadcrumbs should be.

2023-01-16 14:49 UTC, jeremylenz commented on webpack/scenes/Hosts/ChangeContentSource/index.js
> +    const link = singleHost ? { caption: __('Host'), url: foremanUrl(`/new/hosts/${urlParams.host_id[0]}`) } : { caption: __('Hosts'), url: foremanUrl('/hosts') };
When my host id is 28, this link tries to take me to `/new/hosts/2` and not `/new/hosts/28`

2023-01-16 20:02 UTC, chris1984 commented
Once this is merged, I will start work on Katello 4.7.1

2023-01-17 08:45 UTC, stejskalleos commented
@jeremylenz Navigation & texts fixed, for the CV & ENV display I created https://projects.theforeman.org/issues/35958, and added to our backlog

2023-01-17 14:21 UTC, jeremylenz commented
Thanks! Sorry, I didn't mention I had already created https://projects.theforeman.org/issues/35559. I went ahead and marked the duplicate.

2023-01-17 14:25 UTC, jeremylenz approved these changes
thanks @stejskalleos!

APJ, just fix the commit message and then I'll merge it.

2023-01-18 16:25 UTC, merged