Fixes #36943 - reduce the amount of queries to get the errata counts
Katello/katello pull request #10810
Opened 2023-11-24 12:45 UTC by sbernhard

Loading the all hosts page with about 72 hosts.

```
OLD
Completed 200 OK in 9900ms (Views: 8613.5ms | ActiveRecord: 787.6ms | Allocations: 5520271)
Completed 200 OK in 9595ms (Views: 8381.8ms | ActiveRecord: 789.9ms | Allocations: 5524887)
SQL Queries: 195

irb(main):049:0> total=0; 100.times do x=Benchmark.measure { Host.all.each do |h| h.content_facet.nil? || h.content_facet.errata_counts_old end }; total = total + x.total; sleep 0.5; end; puts total;
68.09449500000002

NEW
Completed 200 OK in 10789ms (Views: 9794.5ms | ActiveRecord: 549.5ms | Allocations: 5511210)
Completed 200 OK in 9244ms (Views: 8400.2ms | ActiveRecord: 385.6ms | Allocations: 5511208)
SQL Queries: 65

irb(main):050:0> total=0; 100.times do x=Benchmark.measure { Host.all.each do |h| h.content_facet.nil? || h.content_facet.errata_counts end }; total = total + x.total; sleep 0.5; end; puts total;
37.18352599999951
```

2023-12-22 11:27 UTC, sbernhard commented
foreman rake benchmark for about 80 hosts.

Old
```
irb(main):003:0> total=0; 100.times do x=Benchmark.measure { Host.all.each do |h| h.content_facet.nil? || h.content_facet.errata_counts_old; end }; total = total + x.total; end
=> 100
irb(main):004:0> puts total
37.80042699999998
```

New:
```
irb(main):001:0> total=0; 100.times do x=Benchmark.measure { Host.all.each do |h| h.content_facet.nil? || h.content_facet.errata_counts; end }; total = total + x.total; end
=> 100
irb(main):002:0> puts total
22.924028999999997
```

2023-12-27 15:42 UTC, ekohl approved these changes

2024-01-03 20:16 UTC, ianballou requested changes
Looks like bugfix and security got swapped

2024-01-08 08:06 UTC, sbernhard commented on app/models/katello/host/content_facet.rb
> +          :security => applicable_errata_counts.values_at(*Katello::Erratum::BUGZILLA).compact.sum,
Thanks.  Fixed it.

2024-01-08 20:57 UTC, ianballou commented
[test katello]

2024-01-08 20:58 UTC, ianballou approved these changes
Code looks good, just need the tests to pass.

2024-01-09 14:44 UTC, ekohl commented
@ianballou good eye! I missed that. Tests are now green.

2024-01-09 17:29 UTC, merged