Fixes #37123 - Correct virtual_host subscription facet name in Legacy UI
Katello/katello pull request #10871
Opened 2024-01-30 19:14 UTC by chris1984

#### What are the changes introduced in this pull request?

* We must have changed the name of the `subscription_facet_attributes.virtual_host` from `display_name` to `name` when we were doing stuff in the new UI, because it works fine there but we didn't check the old UI. This fixes that up, so it shows correctly the displays the guest/host mapping.

#### Considerations taken when implementing this change?
* N/A

#### What are the testing steps for this pull request?

* Spin up a 6.15/stream in beaker, need to be on the RH network so you can register a host to your box
* Check out PR
* Create a config for VMware (Ping me for creds if you don't have a login)
* Run the deploy script so it sends the guest/host mapping back
* Register a client to your 6.15/stream box and see if the host/guest mapping works correctly in the legacy UI(if you don't want to spin up a client on vmware or beaker, ping me and I can give you a test client to register.)
* Verify that the guest/host mapping looks correct in the legacy UI

Screenshot before:
![hostmapbefore](https://github.com/Katello/katello/assets/1518655/4772dff2-bb69-4bde-a8ea-0f6d921f21a9)

Screenshot after:
![hostmapafter](https://github.com/Katello/katello/assets/1518655/a8a0c868-8faf-4953-ab5a-485c5b6d2b51)

2024-01-30 20:15 UTC, wbclark approved these changes

2024-01-30 21:19 UTC, jeremylenz reviewed
This was changed to `display_name` recently, in https://github.com/Katello/katello/pull/10538, which is related to https://github.com/theforeman/foreman/pull/9613. I want to make sure we fully understand what caused this, because it's kinda weird to be changing it back so soon..

2024-01-30 21:23 UTC, jeremylenz requested changes
Perhaps we need `displayname` as in https://github.com/Katello/katello/pull/10806/files ? 

let's double-check it

2024-01-30 21:40 UTC, wbclark commented
> This was changed to `display_name` recently, in #10538, which is related to [theforeman/foreman#9613](https://github.com/theforeman/foreman/pull/9613). I want to make sure we fully understand what caused this, because it's kinda weird to be changing it back so soon..

Hmmm, all the other changes in that PR were from `host.name` to `host.display_name`

I wonder if `virtual_host.name` -> `virtual_host.display_name` got caught up accidentally in some find and replace?

2024-01-31 15:16 UTC, chris1984 commented
> > This was changed to `display_name` recently, in #10538, which is related to [theforeman/foreman#9613](https://github.com/theforeman/foreman/pull/9613). I want to make sure we fully understand what caused this, because it's kinda weird to be changing it back so soon..
> 
> Hmmm, all the other changes in that PR were from `host.name` to `host.display_name`
> 
> I wonder if `virtual_host.name` -> `virtual_host.display_name` got caught up accidentally in some find and replace?

That is what happened, I am going to try using short names and see if it makes a difference on the host, if it does not affect the hostname then I think it's fine to switch it, since it's only the old UI.

2024-01-31 15:19 UTC, jeremylenz commented
In Foreman, app/views/api/v2/hosts/base.json.rabl:

```
node :display_name do |host|
  host.to_label
end
```

This means that when looking at a `Host::Managed` API response, it will have a `display_name` node.

In Katello, app/models/katello/host/subscription_facet.rb:

```
      belongs_to :hypervisor_host, :class_name => "::Host::Managed"
```

In app/views/katello/api/v2/subscription_facet/show.json.rabl:

```
child :hypervisor_host => :virtual_host do
    attributes :id, :name
  end
```

This means that in the subscription_facet_attributes API response node, the `virtual_host` will be displayed only with `id` and `name`. I think this explains the discrepancy.

We _could_ make this work with `display_name` as well for consistency by altering that rabl. Or we could leave this as-is. Thoughts?

2024-01-31 15:24 UTC, wbclark commented
> We _could_ make this work with `display_name` as well for consistency by altering that rabl. Or we could leave this as-is. Thoughts?

Thanks @jeremylenz . Could you help me better understand what is the upside vs. effort required for doing so? Is this issue going to come up a different way in the future once the old UI goes away?

2024-01-31 15:25 UTC, jeremylenz commented
@wbclark If we leave it as-is, that would mean this field doesn't respect the "Display FQDN for hosts" setting. We should test that.

2024-01-31 15:30 UTC, chris1984 commented
I am +1 for changing the rabl so it works with the `Display FQDN for hosts` setting. Your thoughts @wbclark ?

2024-01-31 15:32 UTC, wbclark commented
Hmmm, I can understand why some users might prefer to see short names only when looking at all hosts, but maybe there is no reason to care when they are looking up the hypervisor a host is mapped to? Not sure tbh.

If the effort is small and you both want to do it, then IMO go for it.

2024-02-02 15:06 UTC, chris1984 commented
@jeremylenz updated, here is what the object looks like now:

![prhostobject](https://github.com/Katello/katello/assets/1518655/f78baca6-b701-40a4-9043-e9b86061192d)

It works great

2024-02-02 15:13 UTC, chris1984 commented
> awesome! And just double-checking, does it display differently in the web UI based on that setting?

It looks the same as how it used to be before I made any changes, and we broke the old UI:

Old UI:
![hostoldui](https://github.com/Katello/katello/assets/1518655/cc9b69a6-b7ac-4e34-9565-45894b171dc1)

New UI:
![hostnewui](https://github.com/Katello/katello/assets/1518655/c138e321-fc83-465f-ad78-ddb76d208001)

2024-02-02 15:13 UTC, chris1984 commented
oh with the setting :) let me check

2024-02-02 15:16 UTC, chris1984 commented
Yep, it honors the new setting in the old UI :)

![hostsetting](https://github.com/Katello/katello/assets/1518655/c439c9f4-ae00-4448-90d0-cbbcd6d9ccdd)

2024-02-02 15:41 UTC, jeremylenz approved these changes
Nice work! Thanks @chris1984 

APJ :+1: from me

2024-02-09 16:27 UTC, jeremylenz commented
[test katello]

2024-02-12 15:44 UTC, merged