Display multi-CV on host details page
Katello/katello pull request #11004
Opened 2024-05-22 22:16 UTC by jeremylenz

#### What are the changes introduced in this pull request?

#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?

2024-05-31 15:14 UTC, sjha4 commented
I'll test this in a bit but I am a little thin on details here..How do we handle host reassignment when deleting a CV/version? Do you see any changes there?

2024-05-31 15:20 UTC, jeremylenz commented
> How do we handle host reassignment when deleting a CV/version? Do you see any changes there?

That's one of the stories that are not built yet. We may get all or part of it for free, but I haven't looked into it yet.

2024-05-31 16:38 UTC, ianballou reviewed
The more details pop up is getting a little far from the new column:
![image](https://github.com/Katello/katello/assets/14796566/0aab6b93-5943-42c6-b7dc-2bf1dae18467)

2024-05-31 17:01 UTC, jeremylenz commented
> The more details pop up is getting a little far from the new column

Took me a minute to figure out what was happening here. The reason was that the `Popover` was centered on the entire table cell, not just the part of it that has text.

I changed the markup so that the `Popover` wraps only the single `FlexItem`. Should be fixed now.

2024-05-31 18:25 UTC, ianballou requested changes
The link to Default Organization View should be disabled since it's a  CV no one should ever see.

The UI pop up for the CV Environments looks better now!

2024-05-31 18:27 UTC, ianballou commented
Besides ^ I haven't found anything off about the current changes, everything looks sane with the setting off too.

2024-05-31 18:28 UTC, ianballou commented
No worries about users being confused about Content View / LCE vs Content view Environments for people not turning on the multi CV setting? I suppose this addition here is a sneaky way to get users slowly used to the new terminology.

2024-05-31 18:29 UTC, jeremylenz commented
> I suppose this addition here is a sneaky way to get users slowly used to the new terminology.

yeah, that's what I'm going for ;)

2024-05-31 18:42 UTC, jeremylenz commented
> The link to Default Organization View should be disabled since it's a CV no one should ever see.

Should be fixed now!

Also apparently needs to be fixed in master, so I opened https://projects.theforeman.org/issues/37525

2024-05-31 20:49 UTC, ianballou reviewed
Looking really great now!

![image](https://github.com/Katello/katello/assets/14796566/9a53b326-4ed1-4563-8fe0-1ee8ef7c7a1d)




![image](https://github.com/Katello/katello/assets/14796566/85bfcd78-3a19-4408-8501-fe9929dc7e81)

2024-05-31 21:07 UTC, jeremylenz commented
Increased the maxWidth of the popover to accommodate longer content view names. :slightly_smiling_face: 

![image](https://github.com/Katello/katello/assets/22042343/3893474d-22c5-4c14-8253-68a0d4784194)

2024-06-03 20:47 UTC, sjha4 commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ChangeHostCVModal.js
> +          title={__('This host is associated with multiple content view environments. If you assign a lifecycle environment or content view here, the host will be removed from the other environments.
```suggestion
          title={__('This host is associated with multiple content view environments. If you assign a lifecycle environment and content view here, the host will be removed from the other environments.')}
```
Should this be `and`?

2024-06-03 20:54 UTC, sjha4 commented on webpack/ForemanColumnExtensions/index.js
> +              {truncate(contentViewEnvironments.map(cve => cve.candlepin_name).join(', '), 35)}
❤️ Filed a bug for CV UI in other places cause we do not truncate these names everywhere..
https://projects.theforeman.org/issues/37530

2024-06-03 20:56 UTC, sjha4 commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +                      defaultMessage="{count, plural, =0 {Content view environments} one {Content view environment} other {Content view environments}}"
Being picky here for our French customers but does this support translations.. 🇫🇷

2024-06-03 20:58 UTC, sjha4 commented
Minor nitpicks but looks really good overall..

2024-06-04 14:07 UTC, jeremylenz commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ChangeHostCVModal.js
> +          title={__('This host is associated with multiple content view environments. If you assign a lifecycle environment or content view here, the host will be removed from the other environments.
Updated :+1:

2024-06-04 14:29 UTC, jeremylenz commented
updated wording per https://github.com/Katello/katello/pull/11004#discussion_r1625031898

2024-06-05 16:37 UTC, ianballou approved these changes
Working fine for me!

2024-06-05 16:44 UTC, jeremylenz commented
rebased

2024-07-16 13:34 UTC, merged