Fixes #37588 - Change UI wording for immediate REX
Katello/katello pull request #11042
Opened 2024-06-21 14:18 UTC by jeremylenz

#### What are the changes introduced in this pull request?

During community demo it was suggested that the options

- via remote execution
- via customized remote execution

are outdated because they come from a time when `katello-agent` was a third option. It was instead suggested to say 'immediately' for the first option.

I changed it in the two places where we have the wording above:

![image](https://github.com/Katello/katello/assets/22042343/2b15f55a-f559-4671-bfc9-6a77051ad6cb)
![image](https://github.com/Katello/katello/assets/22042343/4d916b1b-2dbd-4945-82de-376f4c5c1708)

#### Considerations taken when implementing this change?

There are also other places where the wording is slightly different:
![image](https://github.com/Katello/katello/assets/22042343/724f12e7-77ce-41e2-a0f3-7db0296df80d)

Should I change the wording in these places too? What should it say? "Install immediately?"

I'm also a bit uneasy because the change to the wording implies that "immediate" isn't remote execution, and "customized" is. Is this a legit concern? If so, what are possible solutions?

#### What are the testing steps for this pull request?

I mean, do whatever you want. No functional changes here.

2024-06-21 15:01 UTC, bangelic commented
@jeremylenz I would just have it say **Install**. Not sure the **immediately** is necessary.

2024-06-21 15:11 UTC, jeremylenz commented
> I would just have it say **Install**. Not sure the **immediately** is necessary.

Not sure what you mean?

"Selected packages will be updated on 2 hosts Install" doesn't make sense.

2024-06-21 17:51 UTC, ekohl commented
> I'm also a bit uneasy because the change to the wording implies that "immediate" isn't remote execution, and "customized" is. Is this a legit concern? If so, what are possible solutions?

I had the exact same feeling. A drop down with 2 options doesn't make a whole lot of sense to me. Is it better and clear enough to instead use a checkbox "Schedule future execution"?

2024-06-21 17:53 UTC, jeremylenz commented
> Is it better and clear enough to instead use a checkbox "Schedule future execution"?

It would, but the REX job wizard lets you customize much more than just execution schedule.

2024-06-21 17:58 UTC, ekohl commented
Then perhaps "Customize execution"? Since we can be fancy with React, you could even render 2 different (natural) sentences, depending on which option is selected. Without a drop down at the end of it.

2024-06-26 14:03 UTC, Lennonka requested changes
How about this?

Can we also change the text on the second picture: "After the prerequisites are met, select how you want to install."

And then immediatelly/after you customize REX

2024-06-26 14:03 UTC, Lennonka commented on webpack/components/extensions/HostDetails/Tabs/TracesTab/EnableTracerModal.js
>      __('via customized remote execution'),
```suggestion
    __('after you customize remote execution'),
```

2024-07-16 21:34 UTC, ianballou commented
> Then perhaps "Customize execution"? Since we can be fancy with React, you could even render 2 different (natural) sentences, depending on which option is selected. Without a drop down at the end of it.

My ideal would be something like this -- rather than a dropdown, you could have a checkbox with something like "Customize remote execution job".

I realize this will require editing the UI in a bunch of places since the dropdown is used a bunch.

If that seems like too much, I actually prefer `via remote execution` and `via customized remote execution`. They are short and to-the-point for having a dropdown with two selection. You know exactly what you're getting.

2024-07-31 14:11 UTC, ianballou commented
There haven't been any comments for a while. I think we should either implement the new button/checkbox/etc here, or close out the PR for now and put the issue back on the backlog.

2024-08-02 20:27 UTC, jeremylenz commented
> close out the PR for now and put the issue back on the backlog.

There seems to be no consensus here, so I'm going to close this for now.

2024-08-02 20:27 UTC, closed without merging