Refs #37678 - Update evr migration to use DSL
Katello/katello pull request #11098
Opened 2024-08-05 15:45 UTC by sjha4

#### What are the changes introduced in this pull request?
The evr migration was using SQL to drop the extension possibly causing privilege issues in EL8 upgrade pipeline in nightlies. 
#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?
To test new installs, run bundle exec rails katello:reset
To test upgrades:
You could follow this on the dev box:
git reset --hard 8fed606fdc2bcd783a8e875aef43273e686c80e5
bundle exec rails katello:reset
Create and sync a repo to test data migration. You could also have some host registered to test data migration on installed_packages table
git checkout this branch
run db:migrate and make sure everything works normally.

2024-08-05 19:03 UTC, ekohl requested changes

2024-08-05 19:03 UTC, ekohl commented on db/migrate/20240624121212_katello_recreate_evr_constructs.rb
>      else
```suggestion
    if extension_enabled?('evr')
```

2024-08-05 19:41 UTC, sjha4 commented on db/migrate/20240624121212_katello_recreate_evr_constructs.rb
> +      disable_extension('evr')
My dev box is at this version: https://github.com/rails/rails/blob/v6.1.7.8/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb which does a cascade by default and doesn't accept the force parameter.

2024-08-05 22:43 UTC, ianballou approved these changes
Worked well for me, tested on a 4.13 to nightly upgrade on Alma 8.

2024-08-05 22:46 UTC, ekohl commented
> Worked well for me, tested on a 4.13 to nightly upgrade on Alma 8.

Did you also upgrade from PostgreSQL 12 to 13? I wouldn't expect this PR to just solve the upgrade issue.

2024-08-05 22:47 UTC, ekohl commented on db/migrate/20240624121212_katello_recreate_evr_constructs.rb
> +      disable_extension('evr')
Oh, so that's something we need to think about when we upgrade. I also now see it should have been `force: :cascade`.

2024-08-06 14:19 UTC, sjha4 commented
@ekohl Do we have any way of running nightlies against PRs? Is that a thing?

2024-08-06 14:35 UTC, ekohl commented
You need to combine https://theforeman.github.io/forklift/development/#packit-pr-builds and https://theforeman.github.io/forklift/testing/#pipeline-testing but I don't know how well it works since it only should be set up on the last install, not the n-2 and n-1 versions.

It's probably easier to start a pipeline, let it fail and then manually install the patched version and rerun `foreman-rake db:migrate`. Command I used to start the pipeline:
```
ansible-playbook pipelines/upgrade_pipeline.yml -e forklift_state=up -e pipeline_os=almalinux8 -e pipeline_type=katello -e pipeline_version=nightly
```

After that you can use `vagrant ssh pipe-up-katello-nightly-almalinux8`.

2024-08-06 15:23 UTC, ianballou commented
After some investigation, it's looking like we may need to drop the evr extension from the database via the installer.

Using `REASSIGN OWNED BY` fails with `ERROR:  cannot reassign ownership of objects owned by role postgres because they are required by the database system`. That appears to be the only way to transfer ownership of an extension.

2024-08-06 15:34 UTC, ianballou commented
This thread might have a way to actually change the ownership (scroll down): https://postgrespro.com/list/thread-id/2333512

2024-08-06 15:40 UTC, ianballou commented
Here's how I fixed it:
```
foreman=# \d pg_extension 
              Table "pg_catalog.pg_extension"
     Column     |  Type   | Collation | Nullable | Default 
----------------+---------+-----------+----------+---------
 oid            | oid     |           | not null | 
 extname        | name    |           | not null | 
 extowner       | oid     |           | not null | 
 extnamespace   | oid     |           | not null | 
 extrelocatable | boolean |           | not null | 
 extversion     | text    | C         | not null | 
 extconfig      | oid[]   |           |          | 
 extcondition   | text[]  | C         |          | 
Indexes:
    "pg_extension_name_index" UNIQUE, btree (extname)
    "pg_extension_oid_index" UNIQUE, btree (oid)

foreman=# select * from pg_extension ;
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 13422 | plpgsql |       10 |           11 | f              | 1.0        |           | 
 16910 | evr     |       10 |         2200 | t              | 0.0.2      |           | 
(2 rows)

foreman=# SELECT oid, rolname
foreman-#      FROM pg_authid
foreman-#  WHERE rolname =  'foreman';
  oid  | rolname 
-------+---------
 18263 | foreman
(1 row)

foreman=# SELECT oid, rolname
     FROM pg_authid
 WHERE rolname =  'postgres';
 oid | rolname  
-----+----------
  10 | postgres
(1 row)

foreman=# update pg_extension set extowner = 18263 where extname = 'evr';
UPDATE 1
foreman=# select * from pg_extension ;                        
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 13422 | plpgsql |       10 |           11 | f              | 1.0        |           | 
 16910 | evr     |    18263 |         2200 | t              | 0.0.2      |           | 
(2 rows)

```

2024-08-06 15:49 UTC, ekohl commented
> Here's how I fixed it:

https://postgrespro.com/list/id/CANu8FiwUHNbRkpVCGRkzqvQZVxTm1v9NsrRWkWU-KKD-W-xfqQ@mail.gmail.com says you also need to update `pg_shdepend`:

```sql
UPDATE pg_shdepend
   SET refobjid = {oid_of_new_owner}
 WHERE refobjid = {oid_of old_owner}
   AND deptype = 'o';
```

And I doubt the user `foreman` has permission to do this.

2024-08-06 15:52 UTC, ianballou commented
The `pg_shdepend` change wasn't necessary for me, but perhaps it left some stale data in the table.

2024-08-06 16:12 UTC, ianballou commented
Some notes on using `pg_shdepend`:

It looks like you can use the `evr` extensions `oid` to find the entry in `pg_shdepend` and then update the `refobjid` to be `foreman` instead of `postgres`.
```
foreman=# select * from pg_extension where extname = 'evr';
  oid  | extname | extowner | extnamespace | extrelocatable | extversion | extconfig | extcondition 
-------+---------+----------+--------------+----------------+------------+-----------+--------------
 23270 | evr     |    16386 |         2200 | t              | 0.0.2      |           | 
(1 row)

foreman=# select * from pg_shdepend where objid = 23270;
 dbid  | classid | objid | objsubid | refclassid | refobjid | deptype 
-------+---------+-------+----------+------------+----------+---------
 16387 |    3079 | 23270 |        0 |       1260 |    16386 | o
(1 row)
```

2024-08-06 16:32 UTC, sjha4 commented
This seemed to be sufficient to drop the extension and upgrade:

```
UPDATE pg_extension
SET extowner = (SELECT oid FROM pg_authid WHERE rolname = 'foreman')
WHERE extname = 'evr';
```

2024-08-06 17:03 UTC, sjha4 commented
Thoughts on something like this: https://github.com/theforeman/foreman-installer/pull/955

2024-08-06 19:09 UTC, ianballou commented
> Thoughts on something like this: [theforeman/foreman-installer#955](https://github.com/theforeman/foreman-installer/pull/955)

I'm okay with this, although maybe we should verify that the `pg_shdepend` bits get dropped when the evr extension is dropped.

External DB users will need to run the same command via our docs at upgrade time.

2024-08-08 15:05 UTC, ianballou commented on db/migrate/20240624121212_katello_recreate_evr_constructs.rb
> +      disable_extension('evr')
Is it more dangerous to switch to using `disable_extension` that could change into a non-cascading removal in the future than to keep using raw SQL?

2024-08-08 15:07 UTC, ianballou commented
Now that we know using the active record method doesn't fix nightly, do we need this PR? I'm a little worried about the method in question turning into a non-cascading drop.

2024-10-24 16:53 UTC, sjha4 commented
Closing. This is not needed anymore. We rewrote the new migration with reviews from here: 
https://github.com/Katello/katello/pull/11159

2024-10-24 16:53 UTC, closed without merging