Fixes # 37785- Race condition during container push
Katello/katello pull request #11129
Opened 2024-09-04 16:46 UTC by sjha4

#### What are the changes introduced in this pull request?
In some cases, container push fails due to a race condition where the same push repo creation is triggered more than once during the push process.
#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?
1. Push a container image to katello.
2. Try multiple times till you see the race condition happen. It might take a few attempts to reproduce this.
3. On this branch, you shouldn't see the race condition happen. You may see a logger statement when the race condition happens and the push should proceed as normal afterwards.

2024-09-09 20:15 UTC, qcjames53 requested changes
Hi Samir! I had plenty of time to test your PR. It looks like you've successfully fixed the race condition for checking whether the repo exists in the db as well as the race condition on repo creation itself (encountered in #10995 ). I spent a lot of time in byebug manually triggering things and wasn't able to hit any other snags. This looks pretty good to me.

While there's a part of me that tries to avoid rescue blocks, I think it's probably the best, easiest solution in this specific case. I don't think the performance hit is going to be huge since we only encounter this action on repo creation.

I had two small requests, but otherwise everything looks great!

2024-09-10 00:11 UTC, sjha4 commented on app/models/katello/glue/pulp/repos.rb
> +        RootRepository.new(repo_param)
Definitely cleaner..will push.. ❤️

2024-09-10 13:37 UTC, qcjames53 commented on app/models/katello/repository.rb
> +      !self.root.docker? || (self.root.is_container_push && self.library_instance?)
That sounds good. I think it's also worth mentioning somehow that we don't have to give a container name to repos which aren't docker repos. Maybe add this at the start?
```
# Only set container name for docker repos. If this is a container-push...
```

2024-09-10 21:03 UTC, qcjames53 approved these changes
This looks great to me, thank you!

2024-09-10 21:11 UTC, qcjames53 commented
I have no idea what is causing all the test failures. Your PR works perfectly fine on my machine (even through db operations) and the failures here appear to be unrelated.

2024-09-11 15:59 UTC, merged