Fixes #37816 - List view_smart_proxies as valid permission for non admin user
Katello/katello pull request #11141
Opened 2024-09-12 20:01 UTC by chris1984

#### What are the changes introduced in this pull request?

* When trying to query smart proxies with curl or hammer on a user that is not an admin, the `view_smart_proxies` permission is needed from Foreman, we did not have this before and would only list Katello permissions. We hard code `view_smart_proxies` here when getting the proxies from Foreman https://github.com/Katello/katello/blob/746bda76b50cbe6a321f17994dcd0cd13d97c49b/app/controllers/katello/api/v2/capsules_controller.rb#L13

#### Considerations taken when implementing this change?

* Make sure you can still see Smart Proxies

#### What are the testing steps for this pull request?
* Create a user with a role that only has `view_capsule_content` and `manage_capsule_content`
* Try to curl and see the error message `curl -k -u unauth:unauth https://localhost/katello/api/capsules/`
* Apply PR
* Try the curl again and see if it shows the missing `view_smart_proxies` permission
* Apply the permission and see if curl completes without an error

2024-09-13 14:10 UTC, vsedmik approved these changes
Works good:
```
$ curl -k -u unauth:unauth https://satellite.redhat.com/katello/api/capsules/
{
  "error": {"message":"Access denied","details":"Missing one of the required permissions: view_smart_proxy, manage_capsule_content, view_capsule_content","missing_permissions":["view_smart_proxy","manage_capsule_content","view_capsule_content"]}
}
$ curl -k -u unauth:unauth https://satellite.redhat.com/katello/api/capsules/2
{
  "error": {"message":"Access denied","details":"Missing one of the required permissions: view_smart_proxy, manage_capsule_content, view_capsule_content","missing_permissions":["view_smart_proxy","manage_capsule_content","view_capsule_content"]}
}
```
(`unauth` is an user with insufficient permissions)

2024-09-13 14:41 UTC, vsedmik requested changes
Should we go plural?

2024-09-13 14:41 UTC, vsedmik commented on lib/katello/permission_creator.rb
> +      @plugin.permission :view_smart_proxy,
```suggestion
      @plugin.permission :view_smart_proxies,
```

2024-09-13 14:43 UTC, chris1984 reviewed
Fixes #37816 - List view_smart_proxies as valid permission for non admin user

2024-09-13 14:54 UTC, vsedmik approved these changes
Looks we are good now. Thanks for the patch!

2024-09-16 20:39 UTC, sjha4 approved these changes
Ack.. 🎉

2024-09-16 21:16 UTC, merged