Sysporpose addon removal
Katello/katello pull request #11196
Opened 2024-10-30 15:53 UTC by chris1984

#### What are the changes introduced in this pull request?

#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?

Seeing what tests blowup since I have removed it all from the backend, UI and db migrations still need to be done.

2024-11-14 21:14 UTC, parthaa commented
can you rebase this ?

2024-11-18 14:49 UTC, chris1984 commented
> can you rebase this ?

Will you review it if I do :) I don't want to play the rebase game if no one is going to review it.

2024-11-18 15:02 UTC, chris1984 commented
> can you rebase this ?

@parthaa updated

2024-11-18 20:44 UTC, jeremylenz reviewed
I am not able to run the down migration:
```
$ bundle exec rails db:migrate:down VERSION=20241101144625

== 20241101144625 RemoveSystemPurposeAddons: reverting ========================
-- create_table(:katello_activation_key_purpose_addons)
rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to create_table.
```

One option would be just to consider this an irreversible migration, delete the `down` method, and rename `up` to `change`.

Other than that everything seems to work as expected. :+1:

2024-11-18 20:44 UTC, jeremylenz commented on db/migrate/20241101144625_remove_system_purpose_addons.rb
> +    drop_table :katello_subscription_facet_purpose_addons
@parthaa Is this going to create problems with https://github.com/chris1984/katello/blob/sysporpose/db/migrate/20190605014649_add_purpose_addons.rb ?

do we need to do the "FakePurposeAddon" thing in that old migration file?

2024-11-18 21:44 UTC, chris1984 commented
> I am not able to run the down migration:
> 
> ```
> $ bundle exec rails db:migrate:down VERSION=20241101144625
> 
> == 20241101144625 RemoveSystemPurposeAddons: reverting ========================
> -- create_table(:katello_activation_key_purpose_addons)
> rails aborted!
> StandardError: An error has occurred, this and all later migrations canceled:
> 
> you can't redefine the primary key column 'id'. To define a custom primary key, pass { id: false } to create_table.
> ```
> 
> One option would be just to consider this an irreversible migration, delete the `down` method, and rename `up` to `change`.
> 
> Other than that everything seems to work as expected. 👍

Since I don't think we are going to be adding these back, might as well as change it to irreversible. I was debating on that but decided to try and be fancy and it blew up.

2024-11-19 17:38 UTC, chris1984 commented
@jeremylenz updated the migration

2024-11-19 18:47 UTC, jeremylenz requested changes
Clicking request changes until the https://github.com/Katello/katello/pull/11196/files#r1847225444 is resolved.

2024-11-19 19:00 UTC, chris1984 commented
> Clicking request changes until the https://github.com/Katello/katello/pull/11196/files#r1847225444 is resolved.

Talked with @parthaa and he had me update that migration to just remove us looping through things and just create the table.

2024-11-19 19:02 UTC, jeremylenz approved these changes

2024-11-20 15:27 UTC, chris1984 commented
Tested on a downstream Satellite with a `--reset` to test the database migration and it passed
```bash
2024-11-19 15:40:27 [INFO  ] [post] Executing hooks in group post
  Success!
  * Satellite is running at https://server.example.com

  * To install an additional Capsule on separate machine continue by running:

      capsule-certs-generate --foreman-proxy-fqdn "$CAPSULE" --certs-tar "/root/$CAPSULE-certs.tar"
  * Capsule is running at https://server.example.com

The full log is at /var/log/foreman-installer/satellite.log
Package versions are being locked.
2024-11-19 15:40:27 [INFO  ] [root] Package versions are being locked.
2024-11-19 15:40:28 [INFO  ] [post] All hooks in group post finished
```

2024-11-20 15:28 UTC, merged

2025-01-20 11:57 UTC, ekohl commented
I see system purpose is still mentioned in the docs. In https://docs.theforeman.org/nightly/Managing_Content/index-katello.html#Managing_Activation_Keys_content-management for example. Is this work tracked?

2025-01-20 14:21 UTC, jeremylenz commented
System purpose addons is only one small part of system purpose. Other syspurpose attributes, (role, usage, SLA) along with release version, are neither deprecated nor removed.

2025-01-20 14:33 UTC, ekohl commented
Yet it is mentioned (though the OracleLinux part is a false positive):
```console
 rg -i addons
guides/common/assembly_importing-content.adoc
58::yum_repo_extras_name: {os_name} {os_major} Addons
59::yum_repo_extras_url: https://yum.oracle.com/repo/OracleLinux/OL{os_major}/addons/x86_64/
70::yum_repo_extras_name: {os_name} {os_major} Addons
71::yum_repo_extras_url: https://yum.oracle.com/repo/OracleLinux/OL{os_major}/addons/x86_64/

guides/common/modules/proc_editing-the-system-purpose-of-a-host.adoc
31:# subscription-manager syspurpose add addons '_your_addon_'

guides/common/modules/proc_creating-an-activation-key.adoc
51:--purpose-addons "_addons_"
```

At least the last one is a hammer command and I think that will break.

2025-01-20 14:54 UTC, chris1984 commented
@ekohl I will make a PR to remove it from the docs today

2025-01-20 15:49 UTC, chris1984 commented
Docs PR https://github.com/theforeman/foreman-documentation/pull/3597