Fixes #37974 - support keep-latest-packages in python
Katello/katello pull request #11202
Opened 2024-11-04 17:41 UTC by sbernhard

The pulp python backend supports keep-latest-packages. This should be available on the UI, too.

#### What are the changes introduced in this pull request?

#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?

2024-11-18 15:02 UTC, ekohl reviewed
Not a complete review, just something that jumped out to me.

2024-11-18 15:56 UTC, sbernhard commented on lib/katello/repository_types/python.rb
> +  generic_remote_option :keep_latest_packages, title: N_("Keep latest packages"), type: Integer, input_type: "number", delimiter: ",", default: 0,
you are right. Thanks. Removed it. Copy & Paste issue.

2024-11-19 21:59 UTC, ianballou reviewed
Functionally this is working well when combined with https://github.com/Katello/katello/pull/11220

However, I found a UI bug. When you look at an existing  repository that has a "Keep latest packages" value, the UI shows it as blank. This issue seems related only to generic content  types that have integer fields.

I'm guessing the fix would live in /home/vagrant/katello/engines/bastion_katello/app/assets/javascripts/bastion_katello/products/details/repositories/details/repository-details-info.controller.js

2024-11-20 19:20 UTC, ianballou approved these changes
Works great, thanks!

2024-11-20 19:21 UTC, ianballou requested changes
Oh actually I missed one thing:

2024-11-20 19:21 UTC, ianballou commented on lib/katello/repository_types/python.rb
> +  generic_remote_option :keep_latest_packages, title: N_("Keep latest packages"), type: Integer, input_type: "number", default: 0,
```suggestion
  generic_remote_option :keep_latest_packages, title: N_("Keep latest packages"), type: :number, input_type: "number", default: 0,
```

2024-11-20 21:17 UTC, sbernhard commented on lib/katello/repository_types/python.rb
> +  generic_remote_option :keep_latest_packages, title: N_("Keep latest packages"), type: Integer, input_type: "number", default: 0,
Good point. Thank you!

2024-11-20 22:36 UTC, ianballou approved these changes
Thanks!

2024-11-21 10:12 UTC, merged