Fixes #38048 - Add rolling content views
Katello/katello pull request #11240
Opened 2024-11-28 12:35 UTC by quba42

Issue: https://projects.theforeman.org/issues/38048

Community discussion: https://community.theforeman.org/t/transparent-content-view-for-limiting-repository-access-in-katello/39389

2024-12-02 14:12 UTC, nadjaheitmann commented
Here is a question to @jeremylenz I guess. 
I saw that you added the content_view_environment controller, recently. I am asking myself if this part of the code needs change: https://github.com/Katello/katello/blob/master/app/views/katello/api/v2/content_view_environments/show.json.rabl#L12 (and maybe some parts that use this code which I don't know :) )

2024-12-02 14:57 UTC, jeremylenz commented
> I am asking myself if this part of the code needs change: https://github.com/Katello/katello/blob/master/app/views/katello/api/v2/content_view_environments/show.json.rabl#L12 (and maybe some parts that use this code which I don't know :) )

A content view environment should be created for each rolling content view. The label would be `Library/<rolling_cv_label>`. (The first part would always be `Library/` since rolling CVs cannot be promoted to other LCEs.)

I would expect that rabl to work "for free" - so `hammer content-view-environment list` would display CVEs for rolling content views with labels like I described above. Is that what you are seeing? (I haven't tested this yet)

2024-12-03 08:51 UTC, quba42 commented
> A content view environment should be created for each rolling content view. The label would be `Library/<rolling_cv_label>`. (The first part would always be `Library/` since rolling CVs cannot be promoted to other LCEs.)

I went and double checked. We are currently doing this by calling `async_task(::Actions::Katello::ContentView::AddToEnvironment, @content_view.create_new_version, @content_view.organization.library)` whenever we create a rolling CV. The resultant `Library/<rolling_cv_label>` environment is created both in the Katello and candlepin DB as expected.

> I would expect that rabl to work "for free" - so `hammer content-view-environment list` would display CVEs for rolling content views with labels like I described above. Is that what you are seeing? (I haven't tested this yet)

I am getting `Error: No such sub-command 'content-view-environment'.` most likely because I am on a test instance based on Katello 4.13.1 right now. My Forklift (which is on the state of this PR) does not have Hammer installed. I will need to try to rectify this.

2024-12-10 13:54 UTC, quba42 commented
We have decided to split out the top commit on this PR into a separate PR and issue:

- https://github.com/Katello/katello/pull/11253
- https://projects.theforeman.org/issues/38076

The reasons for doing so are as follows:

- This is arguably a bug that pre-dates the changes introduced with this PR.
- The fix affects the way the API processes data, and we wanted this to receive the proper attention in review. As part of all the changes on this PR it is too easily overlooked!

2024-12-10 14:06 UTC, quba42 commented
We believe this PR is now "ready for review" (I will undraft it shortly).

To summarize:

- As it stands, this PR requires the following to be merged first: https://github.com/Katello/katello/pull/11253, afterwards it can be rebased on top as a single commit. (Right now the change from #11253 is also part of the branch for this PR).
- There is also an accompanying Hammer PR: https://github.com/Katello/hammer-cli-katello/pull/974
- The full list of authors and co-authors for this PR is: @Manisha15, @nadjaheitmann, @m-bucher, @sbernhard, and @quba42
- The current state has experienced extensive pair programming, ATIX internal review, and ATIX internal manual testing.

2024-12-12 15:19 UTC, jeremylenz reviewed
Looking great!

Tested and working pretty much as expected.
Tested with
- host assigned to multiple content view environments
- attempting to disable RH repo included in rolling CV
- attempting to remove repo from product included in rolling CV
- hammer content-view-environment list

Some outstanding UI things:

On the Red Hat Repositories page when you go to disable a repository, there's a tooltip that says "cannot be deleted because it is a part of a published content view." Should that be updated to say something like "..part of a content view" or "..part of a published or rolling content view"?

I like the icon you chose to denote rolling type (vs. CV/CCV). That should also be updated
- in new All Hosts page (ForemanColumnExtensions)
- on host details ContentViewDetails card

Some more wording (cc @maximiliankolb) and other suggestions below

2025-01-09 15:05 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
To try and keep the formulations consistent with each-other, I now went with:
```
CV:  'Contains repositories. Must be published in a optionally filtered version to be used.'
CCV: 'Contains content views. Must be published in a version to be used.'
RCV: 'Contains repositories. Always serves the latest synced content.'
```

2025-01-09 15:12 UTC, jeremylenz commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
@sjha4 @ianballou Thoughts on this wording?

2025-01-09 15:15 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of regular content views')}
The term "Regular" now still appears on the Details tab as a value displayed for the "Type" field.
The Type currently displays the relevant icon followed by one of "Rolling/Composite/Regular".

Should I make this "Rolling content view/Composite content view/Content view" instead? Or is "Regular" fine for this type label?

2025-01-09 15:15 UTC, jeremylenz commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
How about
```
CV:  'Contains repositories. Versions are published and optionally filtered.'
CCV: 'Contains content views. Versions are published.'
RCV: 'Contains repositories. Always serves the latest synced content, with no versioning or publishing.'

2025-01-09 15:16 UTC, jeremylenz commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of regular content views')}
> Should I make this "Rolling content view/Composite content view/Content view" instead?

Yes, I strongly prefer this.

2025-01-09 15:58 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
Getting this right is pretty hard, but feels worth while to me. :wink:
Your latest CV description now feels perfect. Some more nitpicks for the other two:
```
CV:  'Contains repositories. Versions are published and optionally filtered.'
RCV: 'Contains repositories. Always serves the latest synced content, without the need to publish versions.'
CCV: 'Contains content view versions. You must choose the version to use for each content view.'
```
For the CCV one, I am having a devil of a time deciding if they contain "content view versions" or "content views" (from the users point of view. On the one hand I must always choose either a specific version, or else "Always update to latest version" for each content view I add. On the other hand I end up with a "Content View" tab that lists a list of content views (with a version or at least "Not yet published (automatically updates)" selected. So perhaps one of the following actually captures this best?:
```
CCV: 'Contains content views. You must choose the version to use for each content view.'
CCV: 'Contains content views. You must choose the version to use for each constituent content view.'
```

And yes, this level of nitpicking and discussion still feels worthwhile to me. Once we choose now, we are likely to use those formulations for a long time.

2025-01-09 16:01 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of regular content views')}
Will do. Especially now that the "regular" wording is gone from everywhere else, it feels weird to have it stick around for the type label...

2025-01-09 16:03 UTC, jeremylenz commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
I was trying _really_ hard not to use the term "component content view" which we had decided to stop doing. So the former ("for each content view") would be my vote. :+1:

2025-01-09 16:05 UTC, jeremylenz commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
And between `Contains content view versions` and `Contains content views` - The former is more technically accurate, but the latter is more how a user thinks about it. I really could go either way..

2025-01-09 16:14 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__('Contains a set of versioned and optionally filtered repositories')}
Ok, to come to a decision: Unless I receive any more input I will be going with:
```
CV:  'Contains repositories. Versions are published and optionally filtered.'
CCV: 'Contains content views. You must choose the version to use for each content view.'
RCV: 'Contains repositories. Always serves the latest synced content, without the need to publish versions.'
```

2025-01-10 10:27 UTC, quba42 commented
@jeremylenz The following should now be the only remaining ToDos from the things you mentioned:

> I like the icon you chose to denote rolling type (vs. CV/CCV). That should also be update
> * in new All Hosts page (ForemanColumnExtensions)
> * on host details ContentViewDetails card

I will continue with this on Monday.

2025-01-16 14:48 UTC, quba42 commented
The latest push fixes several UI things including the things mentioned by @jeremylenz. In particular:

- The new UI (all hosts and host details) now uses the rolling CV icon where appropriate.
- The "Default Organization View" in the new UI also uses the rolling CV icon (instead of the icon for a standard CV).
- In both old and new UI rolling CVs no longer link to or list their dummy "Version 1.0". Instead they just display the environment "Library" in those places (similar to the "Default Organization View").

The following screen shot is illustrative of the new state:
![rolling_cv_new_ui](https://github.com/user-attachments/assets/39b5525b-0ac1-4422-a218-494f0d198158)

2025-01-16 15:37 UTC, quba42 commented
Looks like I now broke some UI tests. I don't expect to get around to fixing them before Monday.

2025-01-20 13:15 UTC, quba42 commented
Tests are green, and everything is squished and rebased.
=> Ready for the next (and potentially final) round of review.

My understanding is that the plan is to postpone merging until after Katello 4.16 has branched.
Which I believe is planned for mid February.

So far, and now that https://github.com/Katello/katello/pull/11253 has been merged, this branch has been relatively easy to maintain (no VCR recordings), so I am fine with finalizing review now, and then just occasionally rebasing the branch on top of master as we approach the next Katello branching.

2025-01-27 19:41 UTC, sjha4 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__(contentViewDescriptions.CV)}
Not sure this translation will work..Better to translate strings in contentViewDescriptions directly.

2025-01-27 22:16 UTC, ianballou commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__(contentViewDescriptions.CV)}
It won't work.

2025-01-27 22:54 UTC, ianballou requested changes
Initial testing is generally looking good, some questions:

2025-01-27 22:54 UTC, ianballou commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__(contentViewDescriptions.CV)}
Marking a review on this so we don't forget.

2025-01-27 22:54 UTC, ianballou commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
Why does the default content view show up as rolling? I think I can understand the idea since the default CV acts like a rolling CV, however it is a mismatch with ` ::Katello::ContentView.first.rolling?`.

Since the backend mechanisms are different, I'd prefer to continue having the default content view live as a special, separate CV.

2025-01-27 22:54 UTC, ianballou commented on webpack/scenes/ContentViews/Details/ContentViewDetails.js
> +    dropDownItems.push(<DropdownItem key="copy" ouiaId="cv-copy" onClick={() => { setCopying(true); }} > {__('Copy')}</DropdownItem>);
Why is copying not supported for rolling CVs?

![image](https://github.com/user-attachments/assets/c410cc09-0e1b-4917-b961-7d5b4e35101b)

2025-01-27 22:54 UTC, ianballou commented on app/lib/actions/katello/repository/sync.rb
> +              update_rolling_content_views(repo)
Was having the rolling CV update be asynchronous considered? I suppose it's likely that users won't have many rolling content views, so the sync/upload shouldn't likely be blocked too long, but I'm curious if it was a consideration.

2025-02-05 08:54 UTC, m-bucher commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
Agreed, not sure if this was actually a intended change :innocent:

2025-02-05 09:15 UTC, m-bucher commented on webpack/scenes/ContentViews/Details/ContentViewDetails.js
> +    dropDownItems.push(<DropdownItem key="copy" ouiaId="cv-copy" onClick={() => { setCopying(true); }} > {__('Copy')}</DropdownItem>);
To be honest, I guess we considered it as a follow-up feature (if needed).

2025-02-05 11:00 UTC, nadjaheitmann commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
I think, it actually was intended: https://github.com/Katello/katello/pull/11240#issuecomment-2595928702

2025-02-12 16:41 UTC, ianballou commented on webpack/scenes/ContentViews/Details/ContentViewDetails.js
> +    dropDownItems.push(<DropdownItem key="copy" ouiaId="cv-copy" onClick={() => { setCopying(true); }} > {__('Copy')}</DropdownItem>);
Fine by me.

2025-02-12 16:43 UTC, ianballou commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
A new icon for the default org view is a great future idea. Looks like for now we'll keep the old logo just to not confuse current users.

2025-02-18 13:16 UTC, quba42 commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
I believe using the same icon for default organization view and rolling CVs makes a lot of sense, and is far less confusing than the alternative:

1. The default org view is not very much like a normal CV, but very similar to a rolling CV: Both default org view and rolling CVs do not have CV versions and both of them always use LCENV "Library".
2. Default org view and rolling CV always serve identical content for any given repo they contain. A rolling CV containing every repo on your Katello instance is functionally equivalent to the default org view. They both contain latest greatest synced content in a "rolling release" kind of way. The icon we chose for rolling CVs illustrates this well.
3. I don't think using the same icon for the default org view was ever a conscious or particularly logical choice, I think it just happened by default in the absence of a dedicated icon for the default org view.
4. There are very few places were the default org view is visible in UI (with a icon) to begin with, so making the switch now should have a minimal impact in terms of "confusing existing users because something changed".
5. The similarities between default org and rolling are already affecting the look and feel in the new UI, since both of them display "Library" where normal and composite CVs display "Version X.Y". Having Icons aligning differently breaks up these parallels which can be confusing. Re-posting my screenshot to illustrate this:
   ![image](https://github.com/user-attachments/assets/0fbcde7c-54aa-4a64-bfb2-d5193ae1673f)
6. Given the new UI is still optional now is the chance to make a change (to the extent that it is a disruptive/confusing change at all).

At the end of the day, I don't have a lot of skin in this game. If you still want us to go back to the "default CV icon" for the default organization view, we will, but I did want to post the above arguments one more time for final consideration. :relaxed:

2025-02-18 21:32 UTC, ianballou reviewed
![image](https://github.com/user-attachments/assets/c3441a9f-413a-43c4-8375-565fa1b698f0)

I saw the Default Org View is showing the right icon on the content view environments card, but it's still showing the rolling content view icon in the change content view environments modal.

2025-02-18 21:48 UTC, ianballou commented on app/lib/actions/katello/content_view/refresh_rolling_repo.rb
> +            plan_action(Pulp3::Repository::RefreshDistribution, repository, SmartProxy.pulp_primary)
There's an issue here with container push repositories. They're a bit special because, in Pulp, they cannot be redistributed.
We have special logic in `app/lib/actions/pulp3/orchestration/repository/copy_all_units.rb` that tells our orchestration to copy all of the units of a container push repo at publish time from the library repo to the content view version repo.

So, we have two options here. Either we actually copy content from the container push repositories, or we disallow container push repositories from rolling CVs.

Rolling CVs seem to mostly target content types that use sub-man (yum/deb), so I'd be okay with just disallowing container push repositories for now. Copying content would likely over-complicate this new CV type.

2025-02-19 08:33 UTC, quba42 commented on app/lib/actions/katello/content_view/refresh_rolling_repo.rb
> +            plan_action(Pulp3::Repository::RefreshDistribution, repository, SmartProxy.pulp_primary)
In that case we definitely disallow container push repositories for now. Actually copying content very much breaks the Idea of keeping rolling CVs lightweight, which is an essential part of the feature, since we need "Add/Remove repo" operations to be fast.

2025-02-19 15:09 UTC, ianballou commented on app/lib/actions/katello/content_view/refresh_rolling_repo.rb
> +            plan_action(Pulp3::Repository::RefreshDistribution, repository, SmartProxy.pulp_primary)
I missed your previous comment about using the rolling CV field, let me read that first.

2025-02-19 20:19 UTC, ianballou commented on app/lib/actions/katello/content_view/refresh_rolling_repo.rb
> +            plan_action(Pulp3::Repository::RefreshDistribution, repository, SmartProxy.pulp_primary)
There are container push repositories for the Default org view, that's where the go first once you push them. We save references to the distributions that Pulp creates automatically.

2025-02-19 20:25 UTC, ianballou commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
I'm okay with the rolling CV icon being used for the default org view since it's logically closer. It doesn't matter all that much. My initial comment was mostly around the mismatch between the DB and the UI, since one says it is a rolling CV and the other does not. 

> I don't think using the same icon for the default org view was ever a conscious or particularly logical choice, I think it just happened by default in the absence of a dedicated icon for the default org view.

Yep, pretty much :)

2025-02-19 20:29 UTC, ianballou commented
Latest state of my review since the threads are getting confusing:

- We can move back to using the rolling icon for the default CV, apologies for the confusion there.
- Container push repos need to be disallowed
- Why is `::Actions::Katello::ContentView::AddToEnvironment` async during rolling CV creation?

2025-02-19 20:33 UTC, ianballou commented
An issue around errata applicability not being recalculated when repos inside the rolling CV change was noted on Matrix.

2025-02-20 08:44 UTC, quba42 commented
> An issue around errata applicability not being recalculated when repos inside the rolling CV change was noted on Matrix.

@m-bucher has a fix here, we just did not yet have time to finalize and add it to the PR. Will do so soon.

2025-02-20 21:21 UTC, ianballou commented
Are there any plans to add testing of this feature in Robottelo... @dosas ? :)

2025-02-25 08:40 UTC, m-bucher commented
I have now implemented the changes to fix Errata Applicability (or rather genrate it).
Also I have modified/added code regarding Capsule-sync.

2025-02-26 15:55 UTC, quba42 commented
We found one more issue, namely that `rake katello:correct_repositories` miss-identifies rolling CV repos as being broken because they do not have a corresponding Pulp repo and wants to delete them. This should be easy to fix.

2025-02-26 16:17 UTC, quba42 commented
In the latest state, I:

- Re-added deduplicated contentViewDescriptions, but moved the translations calls to the description strings themselves.
- Made the `katello:correct_repositories` rake task ignore rolling CV repos.
- Went back to using the rolling CV icon for Default Organization View in UI (as discussed above).

This still leaves the following open points:

- Container push repos need to be disallowed
- Why is `::Actions::Katello::ContentView::AddToEnvironment` async during rolling CV creation?

I am not sure how to create a container push repository for testing. Is it just a repo of type "docker" with some option to make it push? Do I need to enable the feature somehow?

I am calling it a day, but am really hoping to finish the final two points tomorrow, at which point I will squish everything together. Could usee some pointers on the "Container push repos" thing.

2025-02-26 16:17 UTC, quba42 commented on webpack/components/extensions/HostDetails/Cards/ContentViewDetailsCard/ContentViewDetailsCard.js
> +        <ContentViewIcon composite={contentView.composite} rolling={contentViewDefault || contentView.rolling} style={{ marginRight: '2px' }} position="left" />
Resolved with the latest push.

2025-02-26 16:18 UTC, quba42 commented on webpack/scenes/ContentViews/Create/CreateContentViewForm.js
> +              {__(contentViewDescriptions.CV)}
I believe this is still resolved with the latest push.

2025-02-27 22:26 UTC, ianballou reviewed
I'm testing smart proxy syncing with rolling CVs. The first sync works fine, I see all of the rolling content views. However, it looks like the rolling CVs don't resync changes (likely unless there's a complete sync). I'm guessing the smart proxy sync histories aren't getting cleared out.

We clear the smart proxy sync history, as an example, during the repository update task:

https://github.com/Katello/katello/blob/master/app/lib/actions/katello/repository/update.rb#L56

2025-02-27 22:35 UTC, ianballou reviewed
On the topic of smart proxies, it looks like the content counts page is loosing the rolling CV repo names:
![image](https://github.com/user-attachments/assets/013144dd-ca5e-4327-9eaf-869161bd9c80)

The repo names on the left in the photo are missing.

2025-02-27 22:42 UTC, ianballou commented on app/lib/actions/katello/content_view/refresh_rolling_repo.rb
> +          repository.last_contents_changed = DateTime.now if repository.version_href != library_instance.version_href
```suggestion
          repository.last_contents_changed = DateTime.now if repository.version_href != library_instance.version_href
          repository.clear_smart_proxy_sync_histories
```

This _might_ be the place to fix the smart proxy syncing issue.

2025-02-28 15:46 UTC, ianballou commented
If at any point it feels like this PR is getting too large, I'd also be okay with moving the feature to tech preview and getting in what we have to avoid rebasing pain. Totally up to y'all contributors.

2025-03-03 17:16 UTC, quba42 commented
The latest change should fix smart-proxy re-sync, and also fixes scenarios where just one repo is being synced to every smart proxy (to then also sync any related rolling cv repos). I still need to do more testing though.

2025-03-03 23:10 UTC, ianballou commented
Great, I can give it a test tomorrow.

2025-03-04 21:18 UTC, ianballou commented
The latest commit seems to have fixed smart proxy syncing :+1:

I still see the content counts issue

I'd be okay with leaving it for a future bugfix if it's a pain.
![image](https://github.com/user-attachments/assets/69a63262-7fcf-458b-ba98-c000b195c674)

2025-03-05 17:23 UTC, quba42 commented
Update: I rebased and squished everything together.

The latest state fixed some more edge cases with smart proxy sync when you have a repo in multiple rolling CVs as well as different variants of smart proxy sync (like optimized sync vs. sync an individual repo that was updated).

The two outstanding issues that were raised during review, that I am still aware of are:

- Missing repo names for rolling CVs on the smart proxy view + update content counts
- Container push repos need to be disallowed

Assuming everything now turns green, I would personally like to take @ianballou up on the offer to leave the two remaining issues for follow up tasks. The main reason is that the PR has grown large and with squishes it is getting hard to see what has changed between pushes for re-review. The other less noble reason is that I will be off work for 4 weeks starting tomorrow. This means @m-bucher will be taking over the remaining two tasks and that will be easier to manage on new limited follow-up PRs.

2025-03-11 18:51 UTC, ianballou approved these changes
I just wrapped up my testing with auto syncing of smart proxies, everything seems to be working well. The only bugs that I noticed were related to the smart proxy content counts, which was agreed to be fixed later.

Thanks for the great contribution!

@m-bucher since you have The Power, I'll leave this for you to merge when you're ready :)

2025-03-12 13:29 UTC, merged

2025-03-12 14:59 UTC, nadjaheitmann commented
I have rebased the hammer-cli-katello PR, it is ready for review :) https://github.com/Katello/hammer-cli-katello/pull/974