Fixes #38083 - Add repository filter to Debian packages page
Katello/katello pull request #11255
Opened 2024-12-11 13:42 UTC by nadjaheitmann

#### What are the changes introduced in this pull request?
Adding repository filter for Deb Packages page: 
![image](https://github.com/user-attachments/assets/30a1f8c2-3ec9-426a-8487-1029b5572b14)

#### Considerations taken when implementing this change?
In Content --> Content Type --> Packages we have a repository filter. We want the same for Deb packages. 

#### What are the testing steps for this pull request?
1) You need Debian Repositories with packages.
2) Go Content --> Content Type --> Deb Packages 
3) Select repository from 'All repositories' selection drop down

2024-12-11 19:13 UTC, ianballou approved these changes
Looks good to me!

2024-12-11 19:14 UTC, ianballou requested changes
Missed the failing test, we can merge once it's fixed:
```
 HeadlessChrome 131.0.0 (Linux 0.0.0) Controller: DebsController should set the repository_id param on Nutupane when a repository is chosen FAILED
	Error: <spyOn> : could not find an object to spy upon for setParams()
	Usage: spyOn(<object>, <methodName>)
	    at UserContext.<anonymous> (/home/runner/work/katello/katello/engines/bastion_katello/test/debs/debs.controller.test.js:69:9)
```

2024-12-12 08:59 UTC, nadjaheitmann commented
Thanks @ianballou! Tests are green now :green_circle: :)

2024-12-12 16:02 UTC, ianballou approved these changes
Looks great, thanks!

2024-12-12 16:02 UTC, merged