Fixes #32862 - the comment is moved to the core
Katello/katello pull request #9422
Opened 2021-06-23 12:59 UTC by ares

see https://projects.theforeman.org/issues/32858 for the change in core
that adds this to the safe list

2021-06-23 13:06 UTC, ofedoren commented
@ares, you then probably want to remove the dsl documentation entry as well :)

https://github.com/Katello/katello/blob/d705496b0fcf8243bb93c7520f9f372facd2cc08/app/models/katello/concerns/host_managed_extensions.rb#L88

2021-06-24 17:01 UTC, jeremylenz requested changes
LGTM except for @ofedoren's feedback above!

2021-06-25 10:28 UTC, ares commented
great catch, updated

2021-06-25 12:03 UTC, ofedoren approved these changes

2021-06-25 13:47 UTC, jeremylenz approved these changes

2021-06-25 19:32 UTC, merged