Fixes #32621 - Update useEffect to useDeepCompareEffect
Katello/katello pull request #9430
Opened 2021-06-25 19:35 UTC by parthaa

2021-06-29 17:01 UTC, jeremylenz requested changes
Tested and everything seems to be working fine :)

The request changes is just so we can move the dependency to `@theforeman/vendor-core`
LGTM otherwise :+1:

2021-07-01 16:44 UTC, jeremylenz commented on webpack/scenes/ContentViews/Details/Histories/ContentViewHistories.js
> +  }, [response], setMetadata, loading, setRows);
@parthaa this one still needs fixing :)

2021-07-01 17:05 UTC, jeremylenz approved these changes
APJ

2021-07-01 17:50 UTC, sjha4 commented
We can merge this and let the foreman-js PR get comments and we can use that if it's accepted. 👍🏽

2021-07-01 17:51 UTC, jeremylenz commented
@parthaa looks like there's 1 test failure, maybe it needs a rebase?

2021-07-02 15:11 UTC, merged

2021-07-05 12:18 UTC, ekohl commented
This broke packaging. https://github.com/theforeman/foreman-packaging/pull/6844 was opened to add it, but it's not clear to me if this should be in foreman-js or not.