Fixes #32972: Drop RegistryResource supporting crane
Katello/katello pull request #9450
Opened 2021-07-09 16:43 UTC by ehelms

2021-07-09 16:52 UTC, ekohl requested changes
Yay for cleaning up, but I think you can cleanup a bit more.

2021-07-09 16:52 UTC, ekohl commented on app/lib/katello/resources/registry.rb
> +            registry_url = uri.to_s
Why is this needed? On line 38 it's parsed again and a new `uri` object created. What's the point?

2021-07-09 16:52 UTC, ekohl commented on app/lib/katello/resources/registry.rb
>              fail Errors::ContainerRegistryNotConfigured unless registry_url
Is this still reachable code? I don't think it is. I think it should fail `unless pulp_primary.setting(SmartProxy::PULP3_FEATURE, 'content_app_url')` is set.

2021-07-09 17:26 UTC, ekohl approved these changes
Now we're getting somewhere :)

2021-07-12 13:45 UTC, jlsherrill commented
code looks good, let me do a quick test

2021-07-12 18:50 UTC, jlsherrill approved these changes

2021-07-12 18:50 UTC, merged