Fixes #33181 - pagination info at the bottom & top
Katello/katello pull request #9549
Opened 2021-08-10 21:33 UTC by parthaa

This commit updates the tablewrapper react component and renders the page controls on both top and bottom of the main table.

2021-08-10 21:34 UTC, parthaa commented
![cv-paging](https://user-images.githubusercontent.com/1069779/128938122-7a0a9946-5c30-4584-9701-8a1e8b694068.png)

2021-08-17 14:02 UTC, jeremylenz commented on webpack/components/Table/TableWrapper.js
> +        {ShowPageControls(PaginationVariant.top)}
A function that returns JSX is a React component. Should be invoked not with `{...}` but instead
```js
<ShowPageControls variant={PaginationVariant.top} />
```

However, I wouldn't have this as a separate component anyway.

2021-08-17 14:06 UTC, jeremylenz commented on webpack/components/Table/TableWrapper.js
> +        {ShowPageControls(PaginationVariant.top)}
Or you may choose to keep it as a separate component.. I don't feel as strongly about that. As long as it's notated correctly ;)

2021-08-17 14:33 UTC, Andrewgdewar requested changes

2021-08-18 17:43 UTC, jeremylenz commented
Think this needs a rebase now.. sorry! :grimacing:

2021-08-18 21:47 UTC, jeremylenz reviewed
Looking good! Didn't test it but just leaving a couple minor code comments

2021-08-18 21:47 UTC, jeremylenz commented on webpack/components/Table/TableWrapper.js
> +  const ShowPageControls = variant => (
I actually like Andrew's name better than mine:
```suggestion
  const PageControls = variant => (
```

2021-08-18 21:47 UTC, jeremylenz commented on webpack/components/Table/TableWrapper.js
> +      <Flex><ShowPageControls variant={PaginationVariant.bottom} /></Flex>
Prefer the child(ren) of `<Flex>` to be on a separate line.. just looks nicer to me

2021-08-18 21:49 UTC, jeremylenz commented
oh, looks like the tests also need to be updated!

2021-08-20 17:09 UTC, jeremylenz commented
@parthaa I'm still seeing the full pagination component at the top. Should be the compact one at the top (without the text field)

2021-08-20 18:06 UTC, jeremylenz approved these changes
Nice work @parthaa 

APJ :+1:

2021-08-20 21:04 UTC, parthaa commented
[test katello]

2021-08-21 05:11 UTC, merged