Fixes #33944 - Restart all traces via UI
Katello/katello pull request #9795
Opened 2021-11-18 01:23 UTC by parthaa

Adds select all bindings to the host traces page.

#### What are the changes introduced in this pull request?

#### Considerations taken when implementing this change?

#### What are the testing steps for this pull request?

2021-11-19 13:11 UTC, jeremylenz requested changes
Thanks @parthaa 

Code looks great!  just one nit below

also, I think you need to add `id` to scoped_search for Traces: I'm getting
```
Warning! error during rendering: Field 'id' not recognized for searching!
```
when I try to run a job.

2021-11-19 13:11 UTC, jeremylenz commented on webpack/components/extensions/HostDetails/Tabs/__tests__/tracesTab.test.js
> +    selectAllCheckbox.click();
I think I remember reading in r-t-l docs somewhere, the best practice now is to import `fireEvent` (in our case from react-testing-lib-wrapper) and then do `fireEvent(click, selectAllCheckbox);`

2021-11-19 17:09 UTC, jeremylenz requested changes
Changes look good but I found another issue

When I select all (and don't deselect any), I get an error
```
Validation failed: Template resolve traces - katello ssh default: Input traces search query: Value can't be blank
```

2021-11-19 20:30 UTC, parthaa commented
> When I select all (and don't deselect any), I get an error

Addressed

2021-11-19 20:36 UTC, jeremylenz approved these changes
It's great!

Thanks @parthaa as always

APJ :+1:

2021-11-21 03:15 UTC, parthaa commented
[test katello]

2021-11-21 04:51 UTC, merged