Fixes #34420 - fix REX errata apply with no inc update
Katello/katello pull request #9933
Opened 2022-02-08 21:37 UTC by jlsherrill

#### What are the changes introduced in this pull request?
Fix applying an errata with remote_execution_by_default=true from the Content > Errata page when an incremental update is not required. 

#### Considerations taken when implementing this change?
The changes here:  https://github.com/Katello/katello/pull/9175/files#diff-9124514bc0e0bfa5963c69825b69c895be7ad00040b77361fa97a6352bd082aa 
originally added support for this, but a bugfix:   https://github.com/Katello/katello/pull/9600/files#diff-9124514bc0e0bfa5963c69825b69c895be7ad00040b77361fa97a6352bd082aaR133   

accidentally removed the ability to apply an errata via REX from the errata page unless you are doing an incremental update.

#### What are the testing steps for this pull request?
set the Setting remote_execution_by_default to true

2022-02-10 16:08 UTC, jeremylenz commented
should probably make sure this still works correctly after https://github.com/Katello/katello/pull/9913 is applied :)

2022-02-14 22:18 UTC, jeremylenz requested changes
![errata_join](https://user-images.githubusercontent.com/22042343/153955910-ce4d05f6-a234-4fd1-be2c-8b74cfae023c.png)

I think a rebase to current master should fix `remote_execution_controller`.

2022-02-14 22:35 UTC, jlsherrill commented
i'll rebase it since its been merged, but you can always rebase locally

2022-02-14 22:37 UTC, jlsherrill commented
done!

2022-02-15 15:12 UTC, jeremylenz approved these changes
Tested with rhel7 installable errata

Before patch: attempted to use katello-agent
After patch: uses REX :heavy_check_mark: 

ACK :+1:

2022-02-15 16:36 UTC, merged